//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Energy_Param_Backup
    {
        public int Energy_ParamId { get; set; }
        public int Energy_ParamGroup1Id { get; set; }
        public string Energy_ParamName { get; set; }
        public int Energy_Param_TypeId { get; set; }
        public bool Energy_ParamValid { get; set; }
    }
}
