//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBF_Param_Num_Val_bak
    {
        public int MBF_Param_Num_ValId { get; set; }
        public int MBF_ParamId { get; set; }
        public int MBF_ValTypeId { get; set; }
        public System.DateTime MBF_Date { get; set; }
        public double MBF_NumVal { get; set; }
    }
}
