//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingParam
    {
        public int OperatingParams_Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> Alternate_TransactionDate { get; set; }
        public Nullable<decimal> AF1_HFO_Firing { get; set; }
        public Nullable<decimal> AF1_Combustion_Air { get; set; }
        public Nullable<decimal> AF1_Draft_Pressure { get; set; }
        public Nullable<decimal> AF2_HFO_Firing { get; set; }
        public Nullable<decimal> AF2_Combustion_Air { get; set; }
        public Nullable<decimal> AF2_Draft_Pressure { get; set; }
        public Nullable<decimal> AF_LPG_Firing { get; set; }
        public Nullable<decimal> AF_Compressed_Air { get; set; }
    }
}
