//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdShift
    {
        public int ProdShiftID { get; set; }
        public string ProdShift1 { get; set; }
        public string ProdShiftVal { get; set; }
        public string ProdShiftDesc { get; set; }
    }
}
