//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_ShiftPot_Values
    {
        public int SFP_ShiftPot_ValuesId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> Pots_Group { get; set; }
        public Nullable<int> Pots_Cooling { get; set; }
        public Nullable<int> Pots_Available { get; set; }
        public Nullable<int> Pots_ForBreaking { get; set; }
    }
}
