//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_mobile_AF_QIGItemCards
    {
        public int AFLotNo { get; set; }
        public Nullable<System.DateTime> AF_ProductionDate { get; set; }
        public Nullable<int> CellCounts { get; set; }
        public string AnodeCustomer { get; set; }
        public Nullable<long> idenRow { get; set; }
    }
}
